name: Build Binary

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build AutoFilm for ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: autofilm
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: autofilm
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            bin: autofilm
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: autofilm
          - os: macOS-latest
            target: x86_64-apple-darwin
            bin: autofilm
          - os: macOS-latest
            target: aarch64-apple-darwin
            bin: autofilm
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: autofilm.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            bin: autofilm.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Upload binary artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
