name: Continuous Integration

on:
  push:
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Unit Testing (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - windows-latest
          - windows-11-arm

    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            alist-client-rs -> alist-client-rs/target

      - name: Test AutoFilm
        run: cargo test --locked

      - name: Test Alist Client
        run: cargo test --locked --manifest-path alist-client-rs/Cargo.toml

  fmt-check:
    name: Rust Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust Format Check
        run: cargo fmt --check
